#ifndef LWCHINESEZODIACSIGNFINDER_SIGNFINDER_HELPERS_HPP
#define LWCHINESEZODIACSIGNFINDER_SIGNFINDER_HELPERS_HPP

class SignFinder_helpers
{

};

#endif //LWCHINESEZODIACSIGNFINDER_SIGNFINDER_HELPERS_HPP
