#ifndef LWCHINESEZODIACSIGNFINDER_SIGNFINDER_HELPERS_HPP
#define LWCHINESEZODIACSIGNFINDER_SIGNFINDER_HELPERS_HPP

class SignFinder_helpers
{
public:
    static int getZodiacSign(const int& year);
};

#endif //LWCHINESEZODIACSIGNFINDER_SIGNFINDER_HELPERS_HPP
